package com.localfriday.app.core.mapper

enum class ErrorCode {
    EMPTY_INPUT,
    INPUT_TOO_LONG,
    MISSING_TIME_INFO,
    IMAGE_TOO_LARGE,
    UNSUPPORTED_IMAGE_FORMAT,
    IN_FLIGHT_CONFLICT,
    DUPLICATE_EVENT,
    PERMISSION_DENIED_CALENDAR,
    PERMISSION_DENIED_MICROPHONE,
    PERMISSION_DENIED_STORAGE,
    MODEL_NOT_FOUND,
    MODEL_NOT_READY,
    MODEL_INFERENCE_TIMEOUT,
    MODEL_INFERENCE_ERROR,
    CALENDAR_PROVIDER_ERROR,
    STT_ERROR,
    NETWORK_UNAVAILABLE,
    SEARCH_TIMEOUT,
    DB_WRITE_ERROR,
    DB_MIGRATION_ERROR,
    EXPORT_FAILED,
    IMPORT_MANIFEST_MISMATCH,
    IMPORT_SCHEMA_MISMATCH,
    INSUFFICIENT_STORAGE
}
